# In-Class Exercise: Sentiment Analysis + Text Classification + Prompt Engineering

**Course:** NLP / Text Mining  
**Total Points:** 30  
**Suggested Time:** about 45 minutes total  
**Dataset:** `sentiment_classification_combined_data.csv`

**Instructions**
- Complete all questions in this notebook.
- Run all cells before submission.
- Keep your answers clear and organized.
- For the prompt engineering part, you do **not** need an API key.

## Part A — Sentiment Analysis with VADER (10 points)
In this part, use **VADER** to compute sentiment scores for the text data.

In [26]:
# Upload the dataset file from your computer (Google Colab)
from google.colab import files
filename = 'sentiment_classification_combined_data.csv'
uploaded = files.upload()
filename = next(iter(uploaded))
print("Uploaded file name:", filename)

Saving sentiment_classification_combined_data.csv to sentiment_classification_combined_data (2).csv
Uploaded file name: sentiment_classification_combined_data (2).csv

### Q1. Load and inspect the dataset (2 points)
Show:
1. the first 5 rows  
2. the shape of the dataset  
3. the column names

In [27]:
# Read the uploaded CSV file
import pandas as pd
df = pd.read_csv(filename)
df.head()
df.shape
df.columns
...

Ellipsis

### Q2. Apply VADER to compute sentiment scores (3 points)
- Import VADER
- Download the lexicon if needed
- Create a new column called `compound`
- Show the first 5 rows of `Text` and `compound`

In [28]:
!pip -q install nltk
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment import SentimentIntensityAnalyzer
sia = SentimentIntensityAnalyzer()

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [29]:
# Write your answer here
df['compound'] = df['Text'].apply(lambda x: sia.polarity_scores(str(x))['compound'])

df[['Text', 'compound']].head()

                                                Text  compound
0  I loved this healthcare AI workshop. The examp...    0.8555
1  This lecture was okay, but some parts were con...   -0.2263
2  The notebook was easy to follow and very pract...    0.4404
3  I did not like the explanation of the model re...   -0.2755
4  The activity was interesting and helped me und...    0.4019

### Q3. Create a sentiment label from the compound score (3 points)
Create a new column called `PredictedSentiment` using this rule:
- `compound >= 0.05` → `positive`
- `compound <= -0.05` → `negative`
- otherwise → `neutral`

Then show the first 10 rows of `Text`, `compound`, and `PredictedSentiment`.

In [30]:
# Write your answer here
def get_sentiment(score):
    if score >= 0.05:
        return 'positive'
    elif score <= -0.05:
        return 'negative'
    else:
        return 'neutral'

df['PredictedSentiment'] = df['compound'].apply(get_sentiment)

df[['Text', 'compound', 'PredictedSentiment']].head()

,Text,compound,PredictedSentiment
0,I loved this healthcare AI workshop. The examp...,0.8555,positive
1,"This lecture was okay, but some parts were con...",-0.2263,negative
2,The notebook was easy to follow and very pract...,0.4404,positive
3,I did not like the explanation of the model re...,-0.2755,negative
4,The activity was interesting and helped me und...,0.4019,positive

### Q4. Compare review score and sentiment (2 points)
Group by `Score` and compute the **average compound score** for each score value.

In [31]:
# Write your answer here
df.groupby('Score')['compound'].mean()

Score
1   -0.507033
2   -0.296125
3   -0.150783
4    0.478340
5    0.621167
Name: compound, dtype: float64

## Part B — Prompt Engineering (10 points)
This part is based on the **Prompt Engineering** notebook. You do **not** need an API key. Focus on writing better prompts using the concepts of **instruction, context, output format, zero-shot, few-shot, and chain-of-thought**.

In [32]:
# Sample texts for the prompt engineering questions
sample_reviews = [
    "The product arrived late and the quality was poor.",
    "Amazing battery life and elegant design.",
    "It is fine for daily use, nothing special."
]
for i, text in enumerate(sample_reviews, start=1):
    print(f"{i}. {text}")

1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

### Q1. Zero-shot classification prompt (3 points)
Write a **zero-shot prompt** that asks an AI model to classify each review as **positive, negative, or neutral**.

Your prompt should include:
- a clear instruction
- the three labels
- a request for a clean output format

Store your prompt in a Python variable called `zero_shot_prompt`, then print it.

In [33]:
# Write your answer here
zero_shot_prompt = """
Classify the sentiment of each review as Positive, Negative, or Neutral.

Reviews:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use.

Return only the labels.
"""
print(zero_shot_prompt)

Classify the sentiment of each review as Positive, Negative, or Neutral.

Reviews:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use.

Return only the labels.

### Q2. Few-shot prompt improvement (3 points)
Now improve the previous prompt by adding **two examples**.

Requirements:
- Store it in a variable called `few_shot_prompt`
- Include 2 input-output examples
- Ask the model to classify the 3 sample reviews after the examples

In [34]:
# Write your answer here
few_shot_prompt = """
Classify the sentiment of each review as Positive, Negative, or Neutral.

Examples:
Review: "The product is terrible and broke quickly."
Sentiment: Negative

Review: "Absolutely fantastic performance and great value."
Sentiment: Positive

Now classify:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use.

Return only the labels.
"""
print(few_shot_prompt)

Classify the sentiment of each review as Positive, Negative, or Neutral.

Examples:
Review: "The product is terrible and broke quickly."
Sentiment: Negative

Review: "Absolutely fantastic performance and great value."
Sentiment: Positive

Now classify:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use.

Return only the labels.

### Q3. Prompt comparison and refinement (4 points)
Create a short table or DataFrame with **three columns**:
- `PromptType`
- `MainFeature`
- `WhyUseful`

Include these three prompt types:
1. Zero-shot
2. Few-shot
3. Chain-of-thought

Then, in **2–3 sentences**, explain which one you would choose for a more difficult text analysis task and why.

In [35]:
# Write your answer here
import pandas as pd

data = {
    "PromptType": ["Zero-shot", "Few-shot", "Refined Prompt"],
    "MainFeature": [
        "No examples provided",
        "Includes examples",
        "Clear instructions with constraints"
    ],
    "WhyUseful": [
        "Simple and fast to use",
        "Improves accuracy using examples",
        "Gives more precise and consistent output"
    ]
}

prompt_df = pd.DataFrame(data)
prompt_df

,PromptType,MainFeature,WhyUseful
0,Zero-shot,No examples provided,Simple and fast to use
1,Few-shot,Includes examples,Improves accuracy using examples
2,Refined Prompt,Clear instructions with constraints,Gives more precise and consistent output

## Reflection (optional, no extra points)
Briefly explain the difference between:
- sentiment analysis
- text classification
- prompt engineering